[package]
name = "fl-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
discord-presence = "1.3.1"
widestring = "1.1.0"

[dependencies.windows]
version = "0.58.0"
features = [
    "Win32_UI_WindowsAndMessaging"
]
