name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Get current version
      id: cargo
      uses: dante-signal31/rust-app-version@v1.2.0
    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: discordloops-${{ steps.cargo.outputs.app_version }}
        path: |
          target/debug/fl-rpc.exe
          config.json
          icon.ico
    
