name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: discordloops-${{ github.event.repository.updated_at }}
        path: |
          target/debug/fl-rpc.exe
          config.json
          icon.ico
    
