name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Format latest commit date
      id: commitdate
      run: echo "::set-output name=date::$('${{ github.event.repository.updated_at}}'.Replace(':', '.'))"
    - name: Copy executable to root folder
      run: Copy-Item "target/release/fl-rpc.exe" -Destination "."
    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: discordloops-${{ steps.commitdate.outputs.date }}
        path: |
          fl-rpc.exe
          config.json
          icon.ico
    
